name: document

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build Webpage
        working-directory: ./docs/
        run: |
            hugo mod init github.com/repo/path
            hugo mod get -u
            hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./book/public
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
